import type { Metadata } from "next";

import Navigation from "@components/Navigation";

import "@styles/_index.scss";

export const metadata: Metadata = {
  title: "Gen Con Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navigation />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
