import type { Metadata } from "next";
import "@styles/_index.scss";

import MainNav from "@components/MainNav";
import Footer from "@components/Footer";

export const metadata: Metadata = {
  title: "GenCon Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <MainNav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
