version: "3.0"

services:
  postgres-db:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_PASSWORD: sample123
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-scripts:/docker-entrypoint-initdb.d"

# TODO figure out how to increase the max grpc message size
  jaeger-trace:
      image: jaegertracing/jaeger:2.1.0
      ports:
        # OpenTelemetry gRPC write port
        - "4317:4317"
        # Jaeger UI
        - "16686:16686"
