import './globals.module.scss'

export const metadata = {
  title: 'GenCon Cal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
