name: Import GenCon Events

on:
  push:
    branches: [ parse-json ]

jobs:
  import-json:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Download Zip File
      run: curl https://www.gencon.com/downloads/events.zip -L -o events.zip
    - name: Unzip file
      run: 7z x events.zip
    - name: Install convert-excel-to-json
      run: npm install -g convert-excel-to-json
    - name: Convert to JSON
      run: convert-excel-to-json --sourceFile="events.xlsx" > ./frontend/assets/events/events-${{ steps.date.outputs.date }}.json
    - uses: EndBug/add-and-commit@v9
      with:
        add: './frontend/assets/events/events-${{ steps.date.outputs.date }}.json'
    - name: 'Count Files'
      id: count
      run: echo "::set-output name=count::$( find ./frontend/assets/events -type f | wc -l)"