name: Import GenCon Events

on:
  push:
    branches: [ parse-json ]

jobs:
  import-json:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      run: |
        echo "STORED_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV |
        echo "${{ env.STORED_DATE }}"
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Download zip file
      run: curl https://www.gencon.com/downloads/events.zip -L -o events.zip
    - name: Unzip file
      run: 7z x events.zip
    - name: Install convert-excel-to-json
      run: npm install -g convert-excel-to-json
    - name: Convert to JSON
      run: convert-excel-to-json --sourceFile="events.xlsx" > ./frontend/assets/events/events.json
    - name: Add new file
      uses: EndBug/add-and-commit@v9
      with:
        add: './frontend/assets/events/events.json'
    - name: Count files
      run: echo "FILE_COUNT=$( find ./frontend/assets/events -type f | wc -l)" >> $GITHUB_ENV
    - name: Find oldest file
      run: echo "OLDEST_FILE=$( find ./frontend/assets/events -type f | head -n 1)" >> $GITHUB_ENV
    - name: Remove oldest file
      if: env.FILE_COUNT > 2
      run: echo "${{ env.OLDEST_FILE }}"