name: Import GenCon Events

on:
  push:
    branches:
      - 59-bug-fix-auto-update-gencon-list
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to update events'
        type: environment
        required: true

jobs:
  import-json:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      run: echo "STORED_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install convert-excel-to-json
      run: npm install -g convert-excel-to-json
    - name: Rename event.json
      run: mv -i ./frontend/assets/events/events.json ./frontend/assets/events/events2.json
    - name: Remove raw data file
      uses: EndBug/add-and-commit@v9
      with:
        remove: './frontend/assets/events/rawEvents.json'
    - name: Download zip file
      run: curl https://www.gencon.com/downloads/events.zip -L -o events.zip
    - name: Unzip file
      run: 7z x events.zip
    - name: Convert to JSON
      run: convert-excel-to-json --sourceFile="events.xlsx" > ./frontend/assets/events/rawEvents.json
    - name: Add new file
      uses: EndBug/add-and-commit@v9
      with:
        add: './frontend/assets/events/events.json'
    - name: Remove xlsx file
      uses: EndBug/add-and-commit@v9
      with:
        remove: 'events.xlsx'
    - name: Remove zip file
      uses: EndBug/add-and-commit@v9
      with:
        remove: 'events.zip'
    - name: Run ParseData.js
      run: node ./frontend/modules/parseData.js > ./frontend/assets/events/events.json
    - name: Add new file
      uses: EndBug/add-and-commit@v9
      with:
        add: './frontend/assets/events/events.json'
    - name: Update last updated date
      uses: jossef/action-set-json-field@v2.1
      with:
        file: ./frontend/assets/events/lastUpdate.json
        field: date
        value: ${{ env.STORED_DATE }}
